import { Email } from './types';

export const INITIAL_EMAILS: Email[] = [
  // Promotions older than 1 month (for Task 1)
  {
    id: 'msg-001',
    sender: 'newsletter@sklep.pl',
    senderName: 'Sklep Online',
    subject: 'Promocja -50% na wszystkie produkty!',
    body: 'Tylko dziś, skorzystaj z naszej mega wyprzedaży. Kliknij poniżej aby zobaczyć oferty. Aby wypisać się z listy kliknij unsubscribe.',
    date: '2026-03-01',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'promotions',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-002',
    sender: 'oferty@allegro.pl',
    senderName: 'Allegro',
    subject: 'Wybrane oferty specjalnie dla Ciebie',
    body: 'Sprawdź nasze najlepsze oferty tego tygodnia. Nie przegap okazji! Unsubscribe from this list.',
    date: '2026-02-15',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'promotions',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-003',
    sender: 'deals@amazon.pl',
    senderName: 'Amazon',
    subject: 'Flash Sale - tylko 24 godziny!',
    body: 'Nie przegap naszej błyskawicznej wyprzedaży. Tysiące produktów z rabatem do 70%. Kliknij unsubscribe aby się wypisać.',
    date: '2026-01-20',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: false,
    starColor: 'none',
    category: 'promotions',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-004',
    sender: 'promo@zalando.pl',
    senderName: 'Zalando',
    subject: 'Ostatnie sztuki w wyprzedaży!',
    body: 'Sprawdź co zostało w naszej wyprzedaży. Dostawa gratis powyżej 200 zł.',
    date: '2026-02-28',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'promotions',
    isArchived: false,
    isTrashed: false,
  },
  // Large attachment emails (for Task 2)
  {
    id: 'msg-005',
    sender: 'jan.kowalski@firma.pl',
    senderName: 'Jan Kowalski',
    subject: 'Raport Q4 2025 - pełna wersja z załącznikami',
    body: 'Cześć,\n\nW załączniku przesyłam raport kwartalny Q4 za rok 2025. Zawiera pełną analizę wyników sprzedaży, marketingu oraz prognozę na Q1 2026.\n\nProszę o zapoznanie się przed piątkowym spotkaniem.\n\nPozdrawiam,\nJan Kowalski',
    date: '2026-05-10',
    hasAttachment: true,
    attachmentSize: 25600000, // 25.6 MB
    attachmentName: 'Raport_Q4_2025_v3_FINAL.pdf',
    labels: ['inbox', 'praca'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-006',
    sender: 'anna.nowak@design.pl',
    senderName: 'Anna Nowak',
    subject: 'Finalne pliki projektu brandingowego',
    body: 'Dzień dobry,\n\nPrzesyłam finalne pliki do projektu brandingowego. W archiwum znajdziesz wszystkie wersje logo, palety kolorów oraz guidelines.\n\nPozdrawiam,\nAnna',
    date: '2026-05-05',
    hasAttachment: true,
    attachmentSize: 18300000, // 18.3 MB
    attachmentName: 'Brand_Identity_FINAL.zip',
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-007',
    sender: 'tomasz.wisniewski@studio.pl',
    senderName: 'Tomasz Wiśniewski',
    subject: 'Materiały wideo z konferencji',
    body: 'Hej,\n\nWrzuciłem nagrania z ostatniej konferencji. Pliki są dość duże, ale jakość jest świetna. Daj znać jak dotarły.\n\nPozdro,\nTomek',
    date: '2026-04-22',
    hasAttachment: true,
    attachmentSize: 52000000, // 52 MB
    attachmentName: 'Konferencja_2026_materialy.zip',
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  // Email for Task 3 (star + label "Projekty")
  {
    id: 'msg-008',
    sender: 'ceo@firma.pl',
    senderName: 'Adam Zieliński (CEO)',
    subject: 'PILNE: Decyzja strategiczna do jutra EOD',
    body: 'Cześć,\n\nPotrzebuję Twojej decyzji w sprawie projektu Alfa do jutra końca dnia. To kwestia priorytetowa dla całego Q3. Proszę o potwierdzenie czy podejmujemy się tego kontraktu.\n\nJeśli masz pytania, zadzwoń bezpośrednio.\n\nAdam',
    date: '2026-05-28',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  // Email for Task 4 (snooze)
  {
    id: 'msg-009',
    sender: 'hr@firma.pl',
    senderName: 'Dział HR',
    subject: 'Przegląd roczny - proszę umówić termin',
    body: 'Dzień dobry,\n\nNadszedł czas na coroczne przeglądy pracownicze. Proszę o umówienie terminu spotkania z przełożonym w ciągu najbliższych 2 tygodni.\n\nFormularz do wypełnienia: [link]\n\nPozdrawiam,\nDział HR',
    date: '2026-05-27',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  // Newsletter emails for Task 5
  {
    id: 'msg-010',
    sender: 'digest@medium.com',
    senderName: 'Medium Daily Digest',
    subject: 'Twój tygodniowy digest - Top 10 artykułów',
    body: 'Oto najlepsze artykuły tego tygodnia z Twoich obserwowanych kategorii...\n\nAby wypisać się z listy mailingowej kliknij tutaj: unsubscribe.',
    date: '2026-05-26',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: false,
    starColor: 'none',
    category: 'updates',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-011',
    sender: 'news@linkedin.com',
    senderName: 'LinkedIn',
    subject: 'Nowości w Twojej sieci kontaktów',
    body: 'Piotr Nowak opublikował nowy artykuł. Anna Kowalska ma nową pracę. Sprawdź co słychać u Twoich kontaktów.\n\nTo stop receiving these emails: unsubscribe.',
    date: '2026-05-25',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'updates',
    isArchived: false,
    isTrashed: false,
  },
  // Regular emails for Task 6 (keyboard shortcuts)
  {
    id: 'msg-012',
    sender: 'piotr.wrobel@team.pl',
    senderName: 'Piotr Wróbel',
    subject: 'Spotkanie jutro o 10:00 - potwierdzenie',
    body: 'Hej,\n\nCzy jutrzejsze spotkanie o 10:00 nadal aktualne? Mam konflikt z innym spotkaniem i musiałbym je przesunąć na 11:00.\n\nDaj znać!\nPiotr',
    date: '2026-05-28',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-013',
    sender: 'marta.lis@firma.pl',
    senderName: 'Marta Liś',
    subject: 'Aktualny status projektu Beta',
    body: 'Cześć,\n\nJak wygląda aktualny status projektu Beta? Potrzebuję info do prezentacji dla zarządu.\n\nDzięki!\nMarta',
    date: '2026-05-27',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-014',
    sender: 'noreply@github.com',
    senderName: 'GitHub',
    subject: '[projekt-alfa] Pull request #42 merged',
    body: 'Pull request #42 "Add user authentication" was merged into main by @jkowalski.\n\nView it on GitHub.',
    date: '2026-05-26',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'updates',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-015',
    sender: 'katarzyna.marek@klient.pl',
    senderName: 'Katarzyna Marek',
    subject: 'Pytanie o ofertę współpracy',
    body: 'Dzień dobry,\n\nZwracam się z zapytaniem o możliwość współpracy w zakresie doradztwa IT. Proszę o przesłanie oferty i cennika usług.\n\nZ poważaniem,\nKatarzyna Marek',
    date: '2026-05-24',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  // Emails from Artur (various dates — for Task 7: oldest from Artur)
  {
    id: 'msg-016',
    sender: 'artur.kowalski@firma.pl',
    senderName: 'Artur Kowalski',
    subject: 'Protokół z zebrania zespołu - wrzesień',
    body: 'Cześć,\n\nPrzesyłam protokół z zebrania zespołu z 15 września. Proszę o zatwierdzenie i ewentualne uwagi do końca tygodnia.\n\nPozdrawiam,\nArtur',
    date: '2025-09-15',
    hasAttachment: true,
    attachmentSize: 240000,
    attachmentName: 'Protokol_zebranie_09_2025.docx',
    labels: ['inbox', 'praca'],
    isRead: true,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-017',
    sender: 'artur.wlodarski@gmail.com',
    senderName: 'Artur Włodarski',
    subject: 'Pytanie o ofertę współpracy na Q1',
    body: 'Dzień dobry,\n\nJestem zainteresowany możliwością współpracy w pierwszym kwartale. Czy mógłby Pan przesłać aktualną ofertę cenową?\n\nZ poważaniem,\nArtur Włodarski',
    date: '2026-01-08',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-018',
    sender: 'artur.malinowski@partner.pl',
    senderName: 'Artur Malinowski',
    subject: 'Potwierdzenie spotkania w sprawie projektu',
    body: 'Hej,\n\nPotwierdzam spotkanie na 25 marca o 14:00 w naszym biurze. Agenda: omówienie postępów projektu i plan na Q2.\n\nDo zobaczenia!\nArtur',
    date: '2026-03-22',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-019',
    sender: 'artur.nowicki@startup.io',
    senderName: 'Artur Nowicki',
    subject: 'Demo naszego produktu - zaproszenie',
    body: 'Cześć,\n\nChciałbym zaprosić Cię na demo naszego nowego produktu. Myślę, że może Cię zainteresować w kontekście automatyzacji procesów.\n\nArtur',
    date: '2026-05-10',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  // Emails in specific date ranges (for Task 8)
  {
    id: 'msg-020',
    sender: 'biuro@konferencja.pl',
    senderName: 'Organizator Konferencji',
    subject: 'Potwierdzenie rejestracji - Tech Summit 2026',
    body: 'Dziękujemy za rejestrację na Tech Summit 2026! Konferencja odbędzie się 15 lutego 2026. Zarezerwuj sobie ten termin.\n\nDo zobaczenia!',
    date: '2026-02-03',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'updates',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-021',
    sender: 'ksiegowosc@firma.pl',
    senderName: 'Dział Księgowości',
    subject: 'Rozliczenie kosztów - luty 2026',
    body: 'Proszę o dostarczenie wydatków z lutego do 10 marca. Wymagane dokumenty: faktury, paragony, polecenia służbowe.\n\nKsiągowość',
    date: '2026-02-28',
    hasAttachment: false,
    labels: ['inbox', 'praca'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  // Email for mute task (noisy thread)
  {
    id: 'msg-022',
    sender: 'wszystkich@firma.pl',
    senderName: 'Wszyscy pracownicy',
    subject: 'Odp: Odp: Odp: Odp: Kto zabrał kubek z kuchni?',
    body: 'UWAGA WSZYSCY: Proszę nie używać cudzych kubków. To już 4. wiadomość w tym wątku. Ktoś musi to zatrzymać...\n\n--- Poprzednia wiadomość ---\nCzy ktoś widział mój niebieski kubek z napisem "Developer"?',
    date: '2026-05-27',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  // ── More Artur emails (older) — task: find oldest from Artur ──────────────
  {
    id: 'msg-023',
    sender: 'artur.brzozowski@agencja.pl',
    senderName: 'Artur Brzozowski',
    subject: 'Umowa ramowa - proszę o podpis',
    body: 'Dzień dobry,\n\nPrzesyłam umowę ramową do podpisu. Termin na odesłanie podpisanego dokumentu to 20 czerwca 2025.\n\nPozdrawiam,\nArtur Brzozowski\nAgencja Kreatywna',
    date: '2025-06-10',
    hasAttachment: true,
    attachmentSize: 180000,
    attachmentName: 'Umowa_ramowa_2025.pdf',
    labels: ['inbox', 'praca'],
    isRead: true,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-024',
    sender: 'artur.wisniewski@consulting.pl',
    senderName: 'Artur Wiśniewski',
    subject: 'Raport roczny 2024 - podsumowanie',
    body: 'Witaj,\n\nPrzesyłam raport roczny za 2024. Wyniki są zadowalające, wzrost o 18% YoY. Chętnie omówię szczegóły na spotkaniu.\n\nPozdrawiam,\nArtur',
    date: '2024-12-01',
    hasAttachment: true,
    attachmentSize: 890000,
    attachmentName: 'Raport_roczny_2024.xlsx',
    labels: ['inbox', 'praca'],
    isRead: true,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-025',
    sender: 'artur.dabek@startup.pl',
    senderName: 'Artur Dąbek',
    subject: 'Zaproszenie do beta testów aplikacji',
    body: 'Hej!\n\nStartujemy z beta testami naszej aplikacji. Jeśli masz 30 minut, bardzo chętnie usłyszałbym Twoją opinię.\n\nDaj znać!\nArtur',
    date: '2025-04-03',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  // ── More emails for date-range task (Jan & Feb 2026) ─────────────────────
  {
    id: 'msg-026',
    sender: 'zarzad@firma.pl',
    senderName: 'Zarząd Firmy',
    subject: 'Nowy regulamin pracy zdalnej - styczeń 2026',
    body: 'Szanowni Państwo,\n\nInformujemy, że od 15 stycznia 2026 wchodzi w życie nowy regulamin pracy zdalnej. Proszę zapoznać się z dokumentem.\n\nZarząd',
    date: '2026-01-10',
    hasAttachment: true,
    attachmentSize: 95000,
    attachmentName: 'Regulamin_praca_zdalna_2026.pdf',
    labels: ['inbox', 'praca'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-027',
    sender: 'it@firma.pl',
    senderName: 'Dział IT',
    subject: 'Planowana przerwa techniczna - 20 stycznia',
    body: 'Informujemy o planowanej przerwie technicznej systemów firmowych w dniu 20 stycznia 2026 (środa) w godzinach 22:00–02:00.\n\nDziękujemy za wyrozumiałość.',
    date: '2026-01-15',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'updates',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-028',
    sender: 'marketing@firma.pl',
    senderName: 'Marketing',
    subject: 'Plan kampanii Q1 2026 - Twoje uwagi?',
    body: 'Cześć!\n\nPrzesyłam do wglądu plan kampanii marketingowej na Q1 2026. Proszę o uwagi do piątku 17 stycznia.\n\nPozdrawiam,\nMarketing',
    date: '2026-01-14',
    hasAttachment: true,
    attachmentSize: 3200000,
    attachmentName: 'Plan_kampanii_Q1_2026.pptx',
    labels: ['inbox', 'praca'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-029',
    sender: 'jan.kowalski@firma.pl',
    senderName: 'Jan Kowalski',
    subject: 'Kick-off projektu Delta - zaproszenie',
    body: 'Cześć,\n\nZapraszam na kick-off projektu Delta, który odbędzie się 5 lutego 2026 o 10:00. Proszę potwierdzić uczestnictwo.\n\nJan',
    date: '2026-02-01',
    hasAttachment: false,
    labels: ['inbox', 'praca'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-030',
    sender: 'faktura@dostawca.pl',
    senderName: 'Dostawca IT',
    subject: 'Faktura VAT 02/2026 - licencje oprogramowania',
    body: 'Szanowni Państwo,\n\nW załączniku przesyłamy fakturę VAT nr 02/2026 za licencje oprogramowania (luty 2026). Termin płatności: 28 lutego 2026.\n\nPozdrawiamy,\nDostawca IT Sp. z o.o.',
    date: '2026-02-10',
    hasAttachment: true,
    attachmentSize: 145000,
    attachmentName: 'Faktura_02_2026.pdf',
    labels: ['inbox', 'praca'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-031',
    sender: 'anna.nowak@design.pl',
    senderName: 'Anna Nowak',
    subject: 'Nowe grafiki do kampanii - luty',
    body: 'Hej,\n\nPrzesyłam gotowe grafiki do kampanii lutowej. Pliki są dostępne w folderze wspólnym. Daj znać jeśli coś do poprawy!\n\nAnna',
    date: '2026-02-12',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-032',
    sender: 'newsletter@branzy.pl',
    senderName: 'Branżowy Newsletter',
    subject: 'Top 5 trendów IT w lutym 2026',
    body: 'W tym wydaniu: AI w produkcji, cyberbezpieczeństwo 2026, nowe frameworki...\n\nAby wypisać się z listy kliknij: unsubscribe',
    date: '2026-02-17',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'updates',
    isArchived: false,
    isTrashed: false,
  },

  // ── Emails for advanced search tasks ─────────────────────────────────────

  // subject: search — emails with specific subject keywords
  {
    id: 'msg-033',
    sender: 'marta.lis@firma.pl',
    senderName: 'Marta Liś',
    subject: 'PILNE: Zmiana terminu prezentacji zarząd',
    body: 'Hej,\n\nMuszę pilnie poinformować, że prezentacja dla zarządu przeniesiona z piątku na czwartek 14:00. Prosimy o potwierdzenie.\n\nMarta',
    date: '2026-05-20',
    hasAttachment: false,
    labels: ['inbox', 'praca'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-034',
    sender: 'ceo@firma.pl',
    senderName: 'Adam Zieliński (CEO)',
    subject: 'PILNE: Spotkanie kryzysowe - dziś o 17:00',
    body: 'Wszyscy liderzy — PILNE spotkanie kryzysowe dziś o 17:00 w sali konferencyjnej A. Temat: awaria systemu produkcyjnego. Obowiązkowe.\n\nAdam',
    date: '2026-05-22',
    hasAttachment: false,
    labels: ['inbox', 'praca'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  // filename: search — various file types
  {
    id: 'msg-035',
    sender: 'anna.nowak@design.pl',
    senderName: 'Anna Nowak',
    subject: 'Umowa o współpracy - podpisz i odeślij',
    body: 'Dzień dobry,\n\nW załączniku umowa o współpracy w formacie PDF. Proszę o podpisanie i odesłanie skanu do piątku.\n\nPozdrawiam,\nAnna',
    date: '2026-05-15',
    hasAttachment: true,
    attachmentSize: 320000,
    attachmentName: 'Umowa_wspolpracy_2026.pdf',
    labels: ['inbox', 'praca'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-036',
    sender: 'it@firma.pl',
    senderName: 'Dział IT',
    subject: 'Nowa polityka haseł - wymagana zmiana',
    body: 'Zgodnie z nową polityką bezpieczeństwa, wszyscy pracownicy zobowiązani są do zmiany haseł do 1 czerwca 2026.\n\nInstrukcja w załączonym pliku PDF.',
    date: '2026-05-18',
    hasAttachment: true,
    attachmentSize: 156000,
    attachmentName: 'Polityka_hasel_2026.pdf',
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'updates',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-037',
    sender: 'ksiegowosc@firma.pl',
    senderName: 'Dział Księgowości',
    subject: 'Zestawienie kosztów Q1 - Excel',
    body: 'W załączniku zestawienie kosztów za Q1 2026 w formacie Excel. Proszę o weryfikację i potwierdzenie zgodności.\n\nKsięgowość',
    date: '2026-04-10',
    hasAttachment: true,
    attachmentSize: 1200000,
    attachmentName: 'Koszty_Q1_2026.xlsx',
    labels: ['inbox', 'praca'],
    isRead: true,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  // OR / {curly} search — emails from Jan AND Anna for OR query
  {
    id: 'msg-038',
    sender: 'jan.kowalski@firma.pl',
    senderName: 'Jan Kowalski',
    subject: 'Wyniki sprzedaży maj 2026',
    body: 'Cześć,\n\nPrzesyłam wyniki sprzedaży za maj. Przekroczyliśmy cel o 12%. Szczegóły w załączniku.\n\nJan',
    date: '2026-05-23',
    hasAttachment: true,
    attachmentSize: 450000,
    attachmentName: 'Sprzedaz_maj_2026.xlsx',
    labels: ['inbox', 'praca'],
    isRead: false,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-039',
    sender: 'anna.nowak@design.pl',
    senderName: 'Anna Nowak',
    subject: 'Nowe logo - 3 propozycje do wyboru',
    body: 'Hej,\n\nPrzygotowałam 3 propozycje nowego logo. Proszę o feedback do środy — mamy deadline w piątek.\n\nAnna',
    date: '2026-05-21',
    hasAttachment: true,
    attachmentSize: 8500000,
    attachmentName: 'Logo_propozycje_v3.zip',
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'primary',
    isArchived: false,
    isTrashed: false,
  },
  // Domain wildcard — more @firma.pl emails
  {
    id: 'msg-040',
    sender: 'biuro@firma.pl',
    senderName: 'Biuro Zarządu',
    subject: 'Przerwa świąteczna - harmonogram pracy',
    body: 'Informujemy, że biuro będzie zamknięte 19-20 czerwca 2026 (Boże Ciało). Godziny pracy w pozostałe dni bez zmian.\n\nBiuro Zarządu',
    date: '2026-05-28',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: false,
    starColor: 'none',
    category: 'updates',
    isArchived: false,
    isTrashed: false,
  },
  {
    id: 'msg-041',
    sender: 'rekrutacja@firma.pl',
    senderName: 'Rekrutacja',
    subject: 'Nowy pracownik w zespole - przywitaj Marka',
    body: 'Z przyjemnością informujemy, że od 1 czerwca dołącza do nas Marek Zawadzki jako Senior Developer. Proszę przywitać go serdecznie!\n\nRekrutacja',
    date: '2026-05-26',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: true,
    starColor: 'none',
    category: 'updates',
    isArchived: false,
    isTrashed: false,
  },
  // Negation task — newsletters to exclude
  {
    id: 'msg-042',
    sender: 'newsletter@techcrunch.com',
    senderName: 'TechCrunch Newsletter',
    subject: 'AI przejmuje rynek oprogramowania',
    body: 'Dzisiejsze najciekawsze newsy ze świata technologii: OpenAI ogłasza GPT-5, Google wydaje Gemini Ultra 2...\n\nUnsubscribe from this newsletter.',
    date: '2026-05-27',
    hasAttachment: false,
    labels: ['inbox'],
    isRead: false,
    starColor: 'none',
    category: 'updates',
    isArchived: false,
    isTrashed: false,
  },
];

export const INITIAL_LABELS = ['praca', 'Projekty', 'Newslettery'];
